version: 1.2
notebooks:
  - name: small_utf8
    path: /notebook.ipynb
    otherFiles:
      - /small_utf8.txt
  - name: big_utf8
    path: /notebook.ipynb
    otherFiles:
      - /big_utf8.txt
  - name: small_binary
    path: /notebook.ipynb
    otherFiles:
      - /small_binary.dat
  - name: big_binary
    path: /notebook.ipynb
    otherFiles:
      - /big_binary.dat
