version: 1.2
notebooks:
  - name: empty
    path: /notebook.ipynb
    otherFiles:
      - /empty.txt
  - name: small_utf8
    path: /notebook.ipynb
    otherFiles:
      - /small_utf8.txt
      - /files/utf-8.txt
      - /files/2-utf-8.txt
      - /files/3-utf-8.txt
      - /files/4-utf-8.txt
      - /files/5-utf-8.txt
      - /files/6-utf-8.txt
      - /files/7-utf-8.txt
      # - /files/8-utf-8.txt
      # - /files/9-utf-8.txt
  - name: big_utf8
    path: /notebook.ipynb
    otherFiles:
      - /big_utf8.txt
  - name: huge_utf8
    path: /notebook.ipynb
    otherFiles:
      - /huge_utf8.txt
  - name: small_binary
    path: /notebook.ipynb
    otherFiles:
      - /small_binary.dat
  - name: big_binary
    path: /notebook.ipynb
    otherFiles:
      - /big_binary.dat
  - name: huge_binary
    path: /notebook.ipynb
    otherFiles:
      - /huge_binary.dat
  - name: big_notebook
    path: /big_notebook.ipynb
